[tool.black]
line-length = 110

[tool.mypy]
warn_return_any = true
warn_unused_configs = true
strict_equality = true
check_untyped_defs = true

[[tool.mypy.overrides]]
module = [
  "src.common.*",
  "src.aoc2022.*"
]
disallow_untyped_defs = true

[[tool.mypy.overrides]]
module = "parse"
ignore_missing_imports = true